### PR TITLE
initial version ready

### PR DESCRIPTION
**Pull request by dhrumil4u360**

### CODE REVIEW

**Comment by dtojikulov** [comment]
Hello! 
The situation looks like that, I've created a trigger with 'Run Created' method. But I am still getting the request for other events. 

https://imgur.com/h3zu3jz
https://imgur.com/ZTx3BJ9
https://imgur.com/YL805yM
https://imgur.com/oH5ZqEp

Look at it and hit me up when you correct it!

**Comment by dhrumil4u360** [comment]
@dtojikulov We have event based filtering ready now.

**Review by dtojikulov — CHANGES_REQUESTED** [review]
In config.json you have a typo, you are specifying wrong methods for runAborted and runTimedout. You need to fix it.

**Comment by dhrumil4u360** [comment]
@dtojikulov Fixed it :)

**Comment by dhrumil4u360** [comment]
@dtojikulov I have changed it to have single method with multiple params now. Although, I am not able to access CI check details....

**Comment by kadosh1000** [comment]
Hi @dhrumil4u360 as you see your test failed. We have started adding new sets of tests on every plugin pull request. 
Currently we only check if the repo is flattened. Meaning, we removed the `src` and `zip` directories, and now the src should be the root directory and there is no need to create the zip.

Please fix it and commit your fix

**Comment by dhrumil4u360** [comment]
@kadosh1000 got it. restructured the same.

**Review by dtojikulov — APPROVED** [review]
Hello!
I have reviewed the trigger, and approving the Pull Request

**Pull request merged**
